# Generated by Django 3.1 on 2020-09-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTaskManagementMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execute_stamp', models.CharField(blank=True, max_length=255, verbose_name='执行时间戳')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='任务ID')),
                ('task_name', models.CharField(blank=True, max_length=255, verbose_name='任务名称')),
                ('status', models.CharField(blank=True, max_length=255, verbose_name='任务状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('total_second', models.IntegerField(blank=True, null=True, verbose_name='总耗时（秒）')),
            ],
            options={
                'db_table': 'yt_005_task_management_main',
            },
        ),
        migrations.CreateModel(
            name='TTestCaseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execute_stamp', models.CharField(blank=True, max_length=255, verbose_name='执行时间戳')),
                ('number', models.CharField(blank=True, max_length=255, verbose_name='测试用例编号')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='测试用例标题')),
                ('project', models.CharField(blank=True, max_length=255, verbose_name='归属项目')),
                ('module', models.CharField(blank=True, max_length=255, verbose_name='归属模块')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='优先级')),
                ('result', models.CharField(blank=True, max_length=255, verbose_name='执行结果')),
                ('remark', models.CharField(blank=True, max_length=1000, verbose_name='结果备注')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='生成时间')),
            ],
            options={
                'db_table': 'yt_005_testcase_result',
            },
        ),
        migrations.CreateModel(
            name='TTestCaseStepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execute_stamp', models.CharField(blank=True, max_length=255, verbose_name='执行时间戳')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='接口实例名称')),
                ('code', models.CharField(blank=True, max_length=255, verbose_name='接口编号')),
                ('request_type', models.CharField(blank=True, max_length=255, verbose_name='请求方式')),
                ('address', models.CharField(blank=True, max_length=2000, verbose_name='请求地址')),
                ('data_type', models.CharField(blank=True, max_length=255, verbose_name='数据格式')),
                ('request_header', models.CharField(blank=True, max_length=2000, null=True, verbose_name='请求头')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='请求体')),
                ('response_header', models.CharField(blank=True, max_length=2000, null=True, verbose_name='响应头')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='响应体')),
                ('result', models.CharField(blank=True, max_length=255, verbose_name='执行结果')),
                ('remark', models.CharField(blank=True, max_length=1000, verbose_name='结果备注')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='生成时间')),
            ],
            options={
                'db_table': 'yt_005_testcase_step_result',
            },
        ),
    ]
