# Generated by Django 3.1 on 2020-09-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_ttaskmanagementmain_ttestcaseresult_ttestcasestepresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttestcasestepresult',
            name='number',
            field=models.CharField(blank=True, max_length=255, verbose_name='测试用例编号'),
        ),
    ]
