# Generated by Django 3.1 on 2020-12-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201009_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMakeCaseMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='名称')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'yt_003_makecase_main',
            },
        ),
        migrations.CreateModel(
            name='TMakeCaseInterfaceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.IntegerField(blank=True, verbose_name='步骤顺序')),
                ('req_addr', models.CharField(blank=True, max_length=255, verbose_name='请求地址')),
                ('req_type', models.CharField(blank=True, max_length=255, verbose_name='请求方式')),
                ('req_header', models.CharField(blank=True, max_length=2000, null=True, verbose_name='请求头')),
                ('req_body', models.TextField(blank=True, null=True, verbose_name='请求体')),
                ('res_header', models.CharField(blank=True, max_length=2000, null=True, verbose_name='响应头')),
                ('res_body', models.TextField(blank=True, null=True, verbose_name='响应体')),
                ('mc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tmakecasemain')),
            ],
            options={
                'db_table': 'yt_003_makecase_interface_list',
            },
        ),
    ]
