# Generated by Django 3.1 on 2020-12-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_tmakecaseinterfacelist_tmakecasemain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmakecaseinterfacelist',
            name='instance_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='接口实例id'),
        ),
    ]
